version: '3.4'

services:
  blogappapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:roi
    networks:
      - blog-network
    depends_on:
      - "postgres"

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: "always"
    container_name: blog-postgresql
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=BlogApp
      - POSTGRES_USER=postgres

    volumes:
      - ${APPDATA}:/var/lib/postgresql/data'
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge    